image: nfcore/gitpod:dev

tasks:
  - name: Install Pixi
    command: |
      sudo chown gitpod -R /home/gitpod/
      curl -fsSL https://pixi.sh/install.sh | bash
      . /home/gitpod/.bashrc

vscode:
  extensions:
    - nf-core.nf-core-extensionpack
    - quarto.quarto
