project:
  type: book

book:
  title: "Assembly project how-to"
  author: "Mahesh Binzer-Panchal"
  date: last-modified
  chapters:
    - preface.qmd
    - index.qmd
    - initialize.qmd
    - launch.qmd
    - monitor.qmd
    - close.qmd
    - summary.qmd
    - references.qmd
  page-navigation: true
  sidebar:
    title: TOC
    search: true

format:
  html:
    theme: flatly

bibliography: references.bib

execute:
  freeze: auto
