project:
  type: book

book:
  title: "How to use this template"
  author: "Mahesh Binzer-Panchal"
  date: last-modified
  chapters:
    - preface.qmd
    - quick_start.qmd
    - summary.qmd
    - references.qmd
  page-navigation: true
  sidebar:
    title: TOC
    search: true

format:
  html:
    theme: cosmo

bibliography: references.bib

execute:
  freeze: auto
