project:
  type: book

book:
  title: "Project standard operating procedures"
  author: "Mahesh Binzer-Panchal"
  date: last-modified
  chapters:
    - preface.qmd
    - index.qmd
    - initialize.qmd
    - launch.qmd
      # - assembly.qmd
      # - annotation.qmd
      # - popgen.qmd
      # - troubleshoot.qmd
      # - newtool.qmd
    - monitor.qmd
    - close.qmd
    - summary.qmd
    - references.qmd
  page-navigation: true
  sidebar:
    title: Protocols
    search: true

format:
  html:
    theme: flatly

bibliography: references.bib

execute:
  freeze: auto
