project:
  type: book

book:
  title: "Project standard operating procedures"
  author: "Mahesh Binzer-Panchal"
  date: last-modified
  page-navigation: true
  sidebar:
    title: Protocols
    search: true
  chapters:
    - preface.qmd
    - index.qmd
    - initialize.qmd
    - launch.qmd
    - monitor.qmd
    - close.qmd
    - references.qmd
  repo-url: https://github.com/NBISweden/assembly-project-template
  repo-actions: [edit, issue]
  repo-subdir: docs/gh-pages

format:
  html:
    toc-depth: 2
    number-depth: 2
    theme: sketchy

bibliography: references.bib

execute:
  freeze: auto
