# FAQ

## Nextflow related

::: {.callout-tip collapse="true" icon=false}
## Do I need to activate an environment to run the pipeline?

No, the `run_nextflow.sh` script should automatically load the environment for you.

:::

::: {.callout-tip collapse="true" icon=false}
## How do I change resources (cpu, memory, time) for a workflow?

If you want to change the resources requested by a Nextflow process,
update the `nextflow.config` in your launch directory (where you run nextflow).
Configuration [process selectors](https://www.nextflow.io/docs/latest/config.html#process-selectors)
are used to select which processes to change resources for. The label for `withName:` can
be the simple process name (e.g., `MERYL_COUNT`), the full process name (e.g., 
`BUILD_MERYL_HIC_DATABASE:MERYL_COUNT`), or a java/groovy regular expression (e.g., 
`.*:MERYL_COUNT`).

Example:
```groovy
process {
  withName: `BUILD_MERYL_HIC_DATABASE:MERYL_COUNT` {
    cpus   = 50
    memory = 250.GB
    time   = 1.d
  }
}
```

:::

::: {.callout-tip collapse="true" icon=false}
## How do I change optional command-line interface (cli) parameters to tools?

Parameters for tools in Nextflow processes are either provided as process `input:`, or using the
`ext.args` process directive, following the [style of nf-core](https://nf-co.re/docs/contributing/components/ext_args).
Mandatory files, Optional files, and mandatory values for running a tool are supplied through process
`input:` in which case there will be a corresponding workflow parameter to supply them if they're user
configurable. In other cases, there are optional command-line flags that could be provided. These
are supplied using the process directive `ext.args` in the `nextflow.config` in your launch directory.

Example:
```groovy
process {
  withName: `BUILD_MERYL_HIC_DATABASE:MERYL_COUNT` {
    ext.args = '-v'
  }
}
```

:::

::: {.callout-tip collapse="true" icon=false}
## How do I use an other branch than the main to run the pipeline?
If you want to test a pull request that was done on https://github.com/NBISweden/Earth-Biogenome-Project-pilot, you can do :
Example :
```
BRANCH=update_report ./run_nextflow.sh
```

:::

