on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - docs/gh-pages/**

name: Quarto Publish

jobs:
  build-deploy:
    if: ${{ github.repository == 'NBISweden/assembly-project-template' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: docs/gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
